import { CERTIFICATE } from '@/types/certification';

export const CERTIFICATIONS: CERTIFICATE[] = [
    {
        name: "CS50's Introduction to Programming with Python",
        issuingOrganization: "CS50",
        issueDate: "2024-06",
        imgSrc: "/images/icons/CS50.jpeg",
        certificateImg: "/images/certificates/CS50P.png",
        credentialID: "54307aef-f8ef-4307-bf8d-e97745bb6e74",
        credentialURL: "https://cs50.harvard.edu/certificates/54307aef-f8ef-4307-bf8d-e97745bb6e74",
        skills: ["Python", "Regular Expressions", "Software Projects"],
        description: "CS50's Introduction to Programming with Python is a Harvard course covering Python fundamentals, including functions, variables, control structures, file I/O, exception handling, and object-oriented programming. It offers hands-on projects, providing a solid foundation for advanced programming skills.",
    },
    {
        name: "CS50's Introduction to Databases with SQL",
        issuingOrganization: "CS50",
        issueDate: "2024-07",
        imgSrc: "/images/icons/CS50.jpeg",
        certificateImg: "/images/certificates/CS50 SQL.png",
        credentialID: "b05011a1-640e-4766-91e7-5175c4bd67d3",
        credentialURL: "https://cs50.harvard.edu/certificates/b05011a1-640e-4766-91e7-5175c4bd67d3",
        skills: ["SQL", "Database Management Systems (DBMS)"],
        description: "CS50's Introduction to Databases with SQL teaches the fundamentals of relational databases, including CRUD operations, data modeling, and normalization. The course covers joining tables, views, and indexing for optimized searches. It introduces SQLite, PostgreSQL, and MySQL, with integration into Python and Java. Real-world assignments provide hands-on experience with database management and optimization.",
    },
    {
        name: "JavaScript (Intermediate) Certificate",
        issuingOrganization: "HackerRank",
        issueDate: "2024-07",
        imgSrc: "/images/icons/hackerRank.jpeg",
        certificateImg: "/images/certificates/javascript_intermediate certificate.png",
        credentialID: "fae225b8eefa",
        credentialURL: "https://www.hackerrank.com/certificates/fae225b8eefa",
        skills: ["JavaScript"],
        description: "This certification covers advanced topics such as Design Patterns, Memory Management, Concurrency Model, and Event Loops in JavaScript.",
    },
    {
        name: "JavaScript (Basic) Certificate",
        issuingOrganization: "HackerRank",
        issueDate: "2024-07",
        imgSrc: "/images/icons/hackerRank.jpeg",
        certificateImg: "/images/certificates/javascript_basic certificate.png",
        credentialID: "5e146e0bab17",
        credentialURL: "https://www.hackerrank.com/certificates/5e146e0bab17",
        skills: ["JavaScript"],
        description: "This certification covers foundational JavaScript topics, including Functions, Currying, Hoisting, Scope, Inheritance, Events, and Error Handling.",
    },
    {
        name: "Java (Basic) Certificate",
        issuingOrganization: "HackerRank",
        issueDate: "2024-07",
        imgSrc: "/images/icons/hackerRank.jpeg",
        certificateImg: "/images/certificates/java_basic certificate.png",
        credentialID: "2faf5ac76b9c",
        credentialURL: "https://www.hackerrank.com/certificates/2faf5ac76b9c",
        skills: ["Java"],
        description: "This certificate covers the fundamentals of Java programming, including classes, data structures, inheritance, and exception handling. It is expected that you are proficient in Java 7 or Java 8.",
    },
];
